---
pihole_image_base_tag: "2025.11.0"
pihole_image_base_tag_old: "2025.08.0"
pihole_nfs_backup_cleanup_period: "60"
pihole_nfs_backup_frequency: "0 1 */15 * *"

pihole_orbital_sync_image_base_tag: "1.8.4"
pihole_orbital_sync_image_base_tag_old: ""

nebula_sync_image_base_tag: "v0.11.0"
nebula_sync_image_base_tag_old: "v0.4.0"

wireguard_image_base_tag: "arm64v8-1.0.20250521-r0-ls91"
wireguard_image_base_tag_old: "arm64v8-1.0.20250521-r0-ls89"
wireguard_nfs_backup_frequency: "0 1 */30 * *"

traefik_image_base_tag: "v3.6.2"
traefik_image_base_tag_old: "v3.5.3"

smtp_relay_image_base_tag: "1.3.0"
smtp_relay_image_base_tag_old: ""

grafana_image_base_tag: "10.0.3-ubuntu"
grafana_image_base_tag_old: "9.3.1-ubuntu"
grafana_nfs_backup_cleanup_period: "60"
grafana_nfs_backup_frequency: "0 1 */15 * *"

prometheus_image_base_tag: "v2.45.0"
prometheus_image_base_tag_old: "v2.40.6"

prometheus_docker_cli_commands:
  "config.file": "/etc/prometheus/prometheus.yml"
  "web.config.file": "/etc/prometheus/web.yml"
  "web.console.libraries": "/usr/share/prometheus/console_libraries"
  "web.console.templates": "/usr/share/prometheus/consoles"
  "web.external-url": "https://prometheus.{{ home_lan_domain }}"
  "storage.tsdb.retention.time": "1y"
  "storage.tsdb.retention.size": "50GB"

snmp_exporter_image_base_tag: "v0.26.0"
snmp_exporter_image_base_tag_old: "v0.22.0"

alertmanager_image_base_tag: "v0.25.0"
alertmanager_image_base_tag_old: "v0.23.0"

### Home Internet monitoring
home_internet_blackbox_exporter_image_base_tag: "v0.24.0"
home_internet_speedtest_exporter_image_base_tag: "v3.5.4"

portainer_image_base_tag: "latest"
portainer_image_base_tag_old: "2.16.2"
# portainer_image_base_tag: "2.16.2"
# portainer_image_base_tag_old: ""

frigate_image_base_tag: "0.16.2"
frigate_image_base_tag_old: "0.15.0"

mqtt_mosquitto_image_base_tag: "2.0.21"
mqtt_mosquitto_image_base_tag_old: "2.0.20"

zigbee2mqtt_image_base_tag: "2.0.0"
zigbee2mqtt_image_base_tag_old: "latest"

zwave_js_ui_image_base_tag: "11.0.1"
zwave_js_ui_image_base_tag_old: "10.6.1"

rtl_433_image_base_tag: "25.02-alpine-3.22"
rtl_433_image_base_tag_old: "22.11-alpine-3.18.2"

meTube_image_base_tag: "latest"
meTube_image_base_tag_old: "2023-07-27"

digikam_image_base_tag: "8.6.0-ls253"
digikam_image_base_tag_old: "8.5.0-ls234"

authelia_image_base_tag: "4.39.13"
authelia_image_base_tag_old: "4.39.4"

### Immich
immich_image_base_tag: "v2.0.1"
immich_image_base_tag_old: "v1.135.3"

immich_redis_image_base_tag: "8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1"
immich_redis_image_base_tag_old: ""

immich_postgres_image_base_tag: "14-vectorchord0.4.3-pgvectors0.2.0"
immich_postgres_image_base_tag_old: "14-vectorchord0.3.0-pgvectors0.2.0"

jellyfin_image_base_tag: "10.10.7"
jellyfin_image_base_tag_old: "20240303.2-unstable"
# jellyfin_image_base_tag: "10.8.10"
# jellyfin_image_base_tag_old: ""

watchtower_image_base_tag: "1.7.1"
watchtower_image_base_tag_old: "1.6.0"

open_speedtest_image_base_tag: "latest"
open_speedtest_image_base_tag_old: ""

### Paperless-ngx

paperless_ngx_image_base_tag: "2.18.4"
paperless_ngx_image_base_tag_old: "2.17.1"

paperless_ngx_postgres_image_base_tag: "16.0-alpine"
paperless_ngx_postgres_image_base_tag_old: ""

paperless_ngx_redis_image_base_tag: "7.4-alpine"
paperless_ngx_redis_image_base_tag_old: ""

stirling_pdf_image_base_tag: "latest"
stirling_pdf_image_base_tag_old: "0.29.0"

homepage_dashboard_image_base_tag: "latest"
homepage_dashboard_image_base_tag_old: "v0.9.10"

it_tools_image_base_tag: "latest"
it_tools_image_base_tag_old: ""

# RYOT

ryot_media_image_base_tag: "v8.2.0"
ryot_media_image_base_tag_old: "v8.0.0"
ryot_media_db_image_base_tag: "16-alpine"
ryot_media_db_image_base_tag_old: ""
