---
- name: "TASK: Verify backup directory"
  stat:
    path: "{{ immich_nfs_backup_directory }}"
  register: stat_backup_dir

- name: "TASK: Assert backup directory exists"
  assert:
    that:
      - stat_backup_dir.stat.isdir is defined
      - stat_backup_dir.stat.isdir
    fail_msg: "Backup directory doesn't exist"
    success_msg: "Backup directory exists"

- name: "TASK: Create {{ immich_container_name }} backup cron job"
  become: true
  template:
    src: immich-backup.j2
    dest: "/etc/cron.d/immich-backup"
    owner: root
    group: root
    mode: 0644

- name: "TASK: Create {{ immich_container_name }} backup script"
  become: true
  template:
    src: "immich-backup.sh.j2"
    dest: "{{ immich_container_data_dir }}/scripts/immich-backup.sh"
    owner: root
    group: root
    mode: 0755
